server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: booking
          uri: http://localhost:8081
          predicates:
            - Path=/bookings/**
        - id: confirm
          uri: http://localhost:8082
          predicates:
            - Path=/confirms/** 
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/** 
        - id: bookinglist
          uri: http://localhost:8088
          predicates:
            - Path=/bookinglist/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: booking
          uri: http://booking:8080
          predicates:
            - Path=/bookings/**
        - id: confirm
          uri: http://confirm:8080
          predicates:
            - Path=/confirms/** 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/** 
        - id: bookinglist
          uri: http://bookinglist:8080
          predicates:
            - Path=/boolinglist/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
